### ISSUE TITLE
Emissão manual redirecionando para o 404

### ISSUE THREAD

**Issue by pablocampina** [webmaniabr/NFeMagento#1]
Estou testando em localhost com os dados padrão do módulo (esses dados seriam para teste de homologação)?

Se sim, tem algo estranho acontecendo, para redirecionar para o 404 quando tento emitir a nota.

**Comment by webmaniabr** [comment]
Pablo, as credenciais de acesso informadas são somente de exemplo, sendo necessário realizar a contratação de um plano para que possamos criar credenciais válidas de acesso. Ao escolher um plano no link [webmania.me/1kDM9hi](http://webmania.me/1kDM9hi) informe o cupom **nfedeveloper16** na página finalizar compra para ter o 1º mês grátis para implementação.

Quando solicitado a emissão de Nota Fiscal é redirecionado para uma página processar a requisição e depois redirecionado novamente para a página de pedidos do administrador. Como ocorreu o erro 404, verifique se o arquivo `/app/code/etc/modules/WebmaniaBR_NFE.xml` está instalado na localização correta.

Caso o erro ainda persista, por favor, envie qual é a versão do seu Magento para que eu possa tentar replicar aqui.

Acabei de atualizar o README para não confundir outros programadores sobre as credenciais de acesso. 

Thyago Silva

**Comment by webmaniabr** [comment]
@pabloworks Conseguiu fazer a integração?

**Comment by webmaniabr** [comment]
@pabloworks Realizamos uma nova atualização que corrige essa falha para emissão manual da NF-e para algumas versões do Magento. Realize o download da nova versão e atualize o módulo no seu Magento.

Abraço
