### ISSUE TITLE
previsao magento 2.2 ?

### ISSUE THREAD

**Issue by wubuyun** [webmaniabr/NFeMagento#4]

**Comment by thiagogalvao** [comment]
Também gostaria de saber como está o roadmap para versão 2.2 do mageno. Preciso de uma solução para NFe e Magento 2.

**Comment by webmaniabr** [comment]
Estamos na fase final de testes. Gostariam de testar o módulo? Assim podemos adaptar conforme as necessidades da sua Loja Virtual e deixar com a compatibilidade perfeita. Por favor, havendo interesse enviem um e-mail para suporte@webmaniabr.com para que possamos enviar o módulo.

Abraço,
Equipe WebmaniaBR

**Comment by webmaniabr** [comment]
@thiagogalvao Lançamos oficialmente o módulo para a versão 2.0, 2.1, 2.2 e 2.3. Segue release: https://github.com/webmaniabr/NFeMagento/releases

**Comment by thiagogalvao** [comment]
Obrigado, irei fazer um teste e avaliar o uso junto com o cliente.
